/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import styled from "styled-components";

const HeaderImage = styled.img`
  height: 25rem;
  width: 100%;
  object-fit: cover;
`;

const Lift = styled.div`
  background: #8980f1;
  padding: 3rem 16rem;
  color: #f8f7fe;
  font-weight: 600;
  text-align: center;
  margin-top: -0.5rem;
`;

const Button = styled.button`
  background: #474747;
  border: none;
  color: #f8f7fe;
  padding: 1rem;
  text-align: center;
  text-decoration: none;
  display: inline-block;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/mdv6ewv.css" />
        <link rel="stylesheet" href="https://use.typekit.net/mdv6ewv.css" />
      </Head>

      <Layout>
        <>
          <HeaderImage
            src={require("../public/images/kansikuva.jpg")}
            alt="kansikuva"
          />

          <Lift>
            <h2>LUUPIN JUHLATILA - BEST THING EVER</h2>
            <p>
              Varaa tästä. Super hyvät diilit! Lorem ipsum dolor sit amet,
              consectetur adipiscing elit. Donec ornare libero vitae mauris
              ornare, et suscipit neque mattis. Donec mollis sapien in neque
              sodales congue. Donec dictum id lectus ac malesuada.
            </p>
            <Button>Tutustu tiloihin</Button>
          </Lift>
        </>
      </Layout>
    </div>
  );
};

export default Home;
