/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import styled from "styled-components";
import Script from "next/script";

const HeaderImage = styled.img`
  height: 25rem;
  width: 100%;
  object-fit: cover;
`;

const Lift = styled.div`
  background: #8980f1;
  padding: 2rem 20%;
  color: #f8f7fe;
  font-weight: 600;
  text-align: center;
  margin-top: -0.5rem;
`;

const InfoContainer = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-gap: 2rem;
  padding: 2rem;
  button {
    text-aling: center;
  }
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/mdv6ewv.css" />
        <link rel="stylesheet" href="https://use.typekit.net/mdv6ewv.css" />
      </Head>
      <Layout>
        <>
          <div id="fb-root"></div>
          <Script
            async
            defer
            crossOrigin="anonymous"
            src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v12.0"
            nonce="dfZGdSf3"
          />
          <HeaderImage
            src={require("../public/images/kansikuva.jpg")}
            alt="kansikuva"
          />

          <Lift>
            <h2>&pi; -KLUBI - BEST THING EVER</h2>
            <p>
              Varaa tästä. Super hyvät diilit! Lorem ipsum dolor sit amet,
              consectetur adipiscing elit. Donec ornare libero vitae mauris
              ornare, et suscipit neque mattis. Donec mollis sapien in neque
              sodales congue. Donec dictum id lectus ac malesuada.
            </p>
            <button>Tutustu tiloihin</button>
          </Lift>
          <InfoContainer>
            <div>
              <p>
                Järjestä juhlat meillä täällä on kaikki mitä tarvitset! Lorem
                ipsum dolor sit amet, consectetur adipiscing elit. Donec ornare
                libero vitae mauris ornare, et suscipit neque mattis. Donec
                mollis sapien in neque sodales congue. Donec dictum id lectus ac
                malesuada.
              </p>
              <button>Varaa tila</button>
            </div>
            <div
              className="fb-page"
              data-href="https://www.facebook.com/piiklubi"
              data-tabs="timeline"
              data-width="1000"
              data-height="400"
              data-small-header="true"
              data-adapt-container-width="true"
              data-hide-cover="false"
              data-show-facepile="false"
            >
              <blockquote
                cite="https://www.facebook.com/piiklubi"
                className="fb-xfbml-parse-ignore"
              >
                <a href="https://www.facebook.com/piiklubi">Pii-Klubi</a>
              </blockquote>
            </div>
          </InfoContainer>
        </>
      </Layout>
    </div>
  );
};

export default Home;
